### ISSUE TITLE
E486: Pattern not found <Plug>(ms_up)

### ISSUE THREAD

**Issue by u0931220** [lacygoill/vim-search#1]
### System Information

_Vim_: 8.2.227

### Vim Configuration

```
call plug#begin('~/.vim/plugged')

    " Index and highlight searches
    Plug 'lacygoill/vim-search'

call plug#end()
```

### Steps to Reproduce

Open a text file, place cursor on a word, and press `*`

### Expected Behavior

Word under the cursor is searched just like normal

### Behavior

Vim displays: `E486: Pattern not found <Plug>(ms_up)`

**Comment by u0931220** [comment]
It seems that this works when performing the `*` action in visual mode, but not in normal mode.

**Comment by lacygoill** [comment]
It's probably because of a [Vim bug](https://github.com/vim/vim/issues/4836).

There are 2 solutions:

   1. set `t_RV` to an empty string in the vimrc:

          set t_RV=

   2. replace `\<plug>(ms_up)` with `\<up>` in [this line](https://github.com/lacygoill/vim-search/blob/71e9cee915a9730d8d15019094d52b7af9605793/autoload/search.vim#L632)

In practice, I never experience this issue, because my `$TERM` is `tmux-256color`; the issue occurs only if `$TERM` is `xterm` or some derivative (like `xterm-256color`).

For the moment, I've decided to [empty `t_RV` in my vimrc](https://github.com/lacygoill/config/blob/7b4849dc49d7bd738fcbaf4296c4618c1b240ce9/.config/nvim/init.vim#L2107-L2186), because if Vim does something unexpected when `$TERM` is `xterm` and `t_RV` is set, I wonder whether it could do other unexpected things.  If one day I notice that making `t_RV` empty creates issues, I'll remove `<plug>(ms_up)` from the plugin.

---

Btw, there are better plugins to customize the search:

   - [vim-slash](https://github.com/junegunn/vim-slash)
   - [vim-searchindex](https://github.com/google/vim-searchindex)
   - [vim-asterisk](https://github.com/haya14busa/vim-asterisk)
   - [is.vim](https://github.com/haya14busa/is.vim)
   - ...

**Comment by u0931220** [comment]
That is an interesting bug, and doing:

```
set t_RV=
```

worked to fix it. Are there real downsides to doing this? I am not familiar with this option and how it affects other parts of Vim.

>there are better plugins to customize the search

I wasn't aware that [is.vim](https://github.com/haya14busa/is.vim) integrated with [vim-anzu](https://github.com/osyo-manga/vim-anzu) in order to provide _both_ current search highlighting _and_ indexes. 

I'll check out some of these other options, but I like this plugin because it _just works_. I also find myself spending a lot of time reading through all of the Vim-oriented stuff that you have posted because it is well documented and I find myself learning a lot.

Thanks for the response/suggestions!

**Comment by lacygoill** [comment]
> Are there real downsides to doing this? I am not familiar with this option and how it affects other parts of Vim.

It contains a sequence which Vim must send to the terminal to request its version.
If it's set with a sequence understood by the terminal, the latter will answer with another sequence which encodes the version.  This answer is stored in the internal variable `v:termresponse`.

For example if I open an xterm terminal, then start Vim with no config:

    vim -Nu NONE

Then ask Vim for the value of `v:termresponse`:

    :echo v:termresponse

I get:

    ^[[>41;322;0c

The syntax of this sequence is documented [here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_):

    CSI > Ps c
              Send Device Attributes (Secondary DA).
                Ps = 0  or omitted -> request the terminal's identification
              code.  The response depends on the decTerminalID resource set-
              ting.  It should apply only to VT220 and up, but xterm extends
              this to VT100.
                -> CSI  > Pp ; Pv ; Pc c
              where Pp denotes the terminal type
                Pp = 0  -> "VT100".
                Pp = 1  -> "VT220".
                Pp = 2  -> "VT240".
                Pp = 1 8 -> "VT330".
                Pp = 1 9 -> "VT340".
                Pp = 2 4 -> "VT320".
                Pp = 4 1 -> "VT420".
                Pp = 6 1 -> "VT510".
                Pp = 6 4 -> "VT520".
                Pp = 6 5 -> "VT525".
              and Pv is the firmware version (for xterm, this was originally
              the XFree86 patch number, starting with 95).  In a DEC termi-
              nal, Pc indicates the ROM cartridge registration number and is
              always zero.

The relevant line is this one:

    CSI  > Pp ; Pv ; Pc c

When compared to my `v:termresponse`, I can extract the reported terminal type (VT420; because `Pp` is `41`) and firmware version (322; because `Pv` is 322).

What does Vim do with this information?  I don't know.  I suspect it influences how Vim sets other terminal options (whose values can be inspected via `:pu=execute('set termcap')`).
So one could think that the issue is somewhere else; in another terminal option wrongly set.  But that's not the case, I've checked in the past.
This means that this information influences Vim's behavior in yet another way; but I don't know which one.

Could it cause issues in the future?  Maybe, but I doubt it.
I try to follow this principle: "remove/disable anything which you don't understand".
I don't understand how `t_RV` influences Vim's behavior, so I disable it.
I don't want to keep something which can have such an unexpected consequence.
If it can break my mapping here, I don't know what else it can break, and I don't want to lose more time debugging weird issues which all stem from the same cause, while not learning anything new in the process.

Maybe one day I'll understand, and realize that it's a safe option which can be set, and all I have to do to fix the issue is correctly set some other option, and perform some minor refactoring.
In the meantime, I disable the option.

For more info, see `:h 't_RV` and `:h v:termresponse`.

---

I don't know which terminal you're using, but if you're not using xterm, then I think you should not be affected by this issue.  If you *are* affected by this issue while using a different terminal, then it probably means that the latter lies about its identity; i.e. `echo $TERM` outputs `xterm` or `xterm-256color`.

Most terminal emulators lie by default about their identity; they claim to be xterm while they are not.  They do that because the `xterm` description is widely supported in most terminfo databases.  Try to run `$ infocmp -1x xterm`, it should work on most if not all machines.  OTOH, `$ infocmp -1x my-exotic-terminal` may work on some machines, and not on others.  So, to avoid issues, many terminal emulators try to be as "xterm-compatible" as possible, then lie, and pretend to be `xterm` via the environment variable `$TERM`.

FWIW, I don't like that, because it may break some assumptions on the part of other programs.  That's why I try to configure most of my terminals so that they report their true identity (unfortunately, this is not always possible).
And I update my terminfo database by running these shell commands whenever I update my OS:

    curl -LO http://invisible-island.net/datafiles/current/terminfo.src.gz
    gunzip terminfo.src.gz
    tic terminfo.src

**Comment by lacygoill** [comment]
See also these help tags:

    :h xterm-8bit
    :h 'ttymouse'
    :h xterm-codes

`t_RV` may have an influence there; for example, Vim may use the answer to set `'ttymouse'`.
I don't care about that, because I already set the option in my vimrc:

    if !has('nvim')
        set ttymouse=sgr
    endif

**Comment by lacygoill** [comment]
Regarding the issue documented at `:h xterm-8bit`:

> Xterm can be run in a mode where it uses 8-bit escape sequences.  The CSI code
> is used instead of <Esc>[.  The advantage is that an <Esc> can quickly be
> recognized in Insert mode, because it can't be confused with the start of a
> special key.

It can be fixed on all terminals by properly setting `'ttimeoutlen'`.  As an example, with this command:

    :set timeout timeoutlen=3000 ttimeoutlen=100

Taken from `:h 'ttimeoutlen`.
